
export const UN_FOLLOW = 'USER_REDUCER_UN_FOLLOW';
export const FOLLOW = 'USER_REDUCER_FOLLOW';
export const SET_USERS = 'USER_REDUCER_SET_USERS';
export const SET_USERS_COUNT = 'USER_REDUCER_SET_USERS_COUNT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const TOGGLE_IS_FATCHING = 'USER_REDUCER_TOGGLE_IS_FATCHING';
export const TOGGLE_IS_FOLLOWING_PROGRESS = 'USER_REDUCER_TOGGLE_IS_FOLLOWING_PROGRESS';



